@startuml

:foo1;
-> You can put text on arrows;

if (test) then
    -[#blue]->
    :foo2;
    -[#green]-> The text can
    also be on several lines
    and **very** long...;
    :foo3;
else
    -[#black]->
    :foo4;
endif

-[#gray]-> test;
:foo5;

@enduml

